name: Publish Package
on:
  release:
    types: [created]
jobs:
  snapshot:
    name: 'Publish Release'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Set Version
        id: set_version
        uses: actions/github-script@v4
        with:
          script: |
            const noRef = context.ref.replace('refs/tags/', '')
            const noPrefix = noRef.replace('v', '')
            core.setOutput('version', noPrefix)
      - name: Publish Release
        run: |
          export GPG_SIGNING_KEY=$(echo -n "$GPG_SIGNING_KEY_BASE64" | base64 -d)
          ./gradlew publish -Pversion=${{steps.set_version.outputs.version}}
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}
          GPG_SIGNING_KEY_BASE64: ${{ secrets.GPG_SIGNING_KEY_BASE64 }}
          GPG_SIGNING_PASSWORD: ${{ secrets.GPG_SIGNING_PASSWORD }}